name: Deploy Guardacivil

on:
  push:
    branches: [main]  # ou 'master', se for sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código (sem submódulos)
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Exibir estrutura do projeto
        run: ls -R
